### ISSUE TITLE
Add support for bind param with value `NULL`

### ISSUE THREAD

**Issue by sayap** [gatling-cql/GatlingCql#14]
I would like to use GatlingCql to simulate the anti-pattern of unnecessary inserting `NULL` (and thus tombstone) when the column should just be omitted from the statement.

With 0.0.6, I get the following error when trying to bind `null` to a prepared statement (e.g. `.withParams("somekey", null)`):
```
java.lang.NullPointerException: null
        at io.github.gatling.cql.BoundCqlStatement$$anonfun$1.apply(CqlStatement.scala:44)
        at io.github.gatling.cql.BoundCqlStatement$$anonfun$1.apply(CqlStatement.scala:44)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at io.github.gatling.cql.BoundCqlStatement.apply(CqlStatement.scala:44)
```
I was able to get past the error with some very ugly hack. Would prefer to have proper support instead :)

While it doesn't look like cassandra-stress supports inserting `NULL` either, I think it will be a good addition for completeness.

**Comment by Mishail** [comment]
Should be fixed by b471f399e97d67fa193b853a55d0726f378aa422
