### ISSUE TITLE
Issues with ssl and gatling 2.3.x

### ISSUE THREAD

**Issue by netalien** [gatling-cql/GatlingCql#18]
Hi,

We experience an issue while trying to use gatling-cql-0.0.7 with gatling-2.3.1 (binary) and cassandra's SSL configuration.

This issue **doesn't happen** using gatling-cql-0.0.7 and gatling-2.2.4, and **doesn't happen** with the new version of gatling (2.3.1) if we **don't use** SSL.

The following trace was observed:

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/gatling/core/check/extractor/SingleArity$class
at io.github.gatling.cql.checks.CqlCheckBuilder$$anon$1.<init>(CqlCheckBuilder.scala:42)
at io.github.gatling.cql.checks.CqlCheckBuilder$.<init>(CqlCheckBuilder.scala:42)
at io.github.gatling.cql.checks.CqlCheckBuilder$.<clinit>(CqlCheckBuilder.scala)
at io.github.gatling.cql.checks.CqlCheckSupport$class.$init$(CqlCheckSupport.scala:32)
at io.github.gatling.cql.Predef$.<init>(Predef.scala:29)
at io.github.gatling.cql.Predef$.<clinit>(Predef.scala)
at cassandra.CassandraSimulation.<init>(CassandraSimulation.scala:41)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at java.lang.Class.newInstance(Unknown Source)
at io.gatling.app.Runner.run0(Runner.scala:79)
at io.gatling.app.Runner.run(Runner.scala:64)
at io.gatling.app.Gatling$.start(Gatling.scala:63)
at io.gatling.app.Gatling$.fromMap(Gatling.scala:40)
at Engine$.delayedEndpoint$Engine$1(Engine.scala:11)
at Engine$delayedInit$body.apply(Engine.scala:4)
at scala.Function0.apply$mcV$sp(Function0.scala:34)
at scala.Function0.apply$mcV$sp$(Function0.scala:34)
at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
at scala.App.$anonfun$main$1$adapted(App.scala:76)
at scala.collection.immutable.List.foreach(List.scala:389)
at scala.App.main(App.scala:76)
at scala.App.main$(App.scala:74)
at Engine$.main(Engine.scala:4)
at Engine.main(Engine.scala)
Caused by: java.lang.ClassNotFoundException: io.gatling.core.check.extractor.SingleArity$class
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 27 more
```

SingleArity is defined as a trait in [CheckBuilder.scala](https://github.com/gatling/gatling/blob/2.3/gatling-core/src/main/scala/io/gatling/core/check/CheckBuilder.scala), the same as it is defined in version 2.2.x of gatling, however for some reason doesn't work with gatling 2.3.x

We manage to get it working by changing the properties _gatling.version_ to 2.3.1 and _scala.version_ to 2.12.3 in gatling-cql's pom.xml and generating a new artifact.

Could you guys check it out?

**Comment by Mishail** [comment]
Yeah, I was thinking about cutting a new release with gatling 2.3.x
