### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContextBuilder.protocols

### ISSUE THREAD

**Issue by vbachurin** [gatling-cql/GatlingCql#19]
I have come upon the following exception when adding the latest GatlingCql-0.0.8.jar into the lib/ directory (even not Cassandra-related simulations do not work due to this issue):

```
java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContextBuilder.protocols([Ljava/lang/String;)Lio/netty/handler/ssl/SslContextBuilder;
	at io.gatling.http.util.SslContextsFactory.newSslContexts(SslContexts.scala:77)
	at io.gatling.http.engine.DefaultHttpClientFactory.newSslContexts(HttpClientFactory.scala:86)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClientConfig(HttpClientFactory.scala:60)
	at io.gatling.http.engine.DefaultHttpClientFactory.newClient(HttpClientFactory.scala:80)
	at io.gatling.http.engine.HttpEngine$.apply(HttpEngine.scala:47)
	at io.gatling.http.protocol.HttpProtocol$$anon$1.newComponents(HttpProtocol.scala:54)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$1(Protocol.scala:68)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.componentsFactory$1(Protocol.scala:68)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.comps$1(Protocol.scala:70)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.$anonfun$components$4(Protocol.scala:72)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at io.gatling.core.protocol.ProtocolComponentsRegistry.components(Protocol.scala:72)
	at io.gatling.http.action.HttpActionBuilder.lookUpHttpComponents(HttpActionBuilder.scala:26)
	at io.gatling.http.action.HttpRequestActionBuilder.build(HttpRequestActionBuilder.scala:33)
	at io.gatling.core.structure.StructureBuilder.$anonfun$build$1(StructureBuilder.scala:35)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:85)
	at io.gatling.core.structure.StructureBuilder.build(StructureBuilder.scala:34)
	at io.gatling.core.structure.StructureBuilder.build$(StructureBuilder.scala:33)
	at io.gatling.core.structure.ScenarioBuilder.build(ScenarioBuilder.scala:38)
	at io.gatling.core.structure.PopulationBuilder.build(ScenarioBuilder.scala:100)
	at io.gatling.core.scenario.SimulationParams.$anonfun$scenarios$1(Simulation.scala:194)
	at scala.collection.immutable.List.map(List.scala:282)
	at io.gatling.core.scenario.SimulationParams.scenarios(Simulation.scala:194)
	at io.gatling.app.Runner.run0(Runner.scala:92)
	at io.gatling.app.Runner.run(Runner.scala:61)
	at io.gatling.app.Gatling$.start(Gatling.scala:74)
	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:47)
	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:52)
	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:51)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] Uncaught exception when running computerdatabase.BasicSimulation: java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContextBuilder.protocols([Ljava/lang/String;)Lio/netty/handler/ssl/SslContextBuilder;
```

Steps to reproduce:
1. Create the SBT project with the latest Gatling using G8:
```
$ sbt new gatling/gatling.g8
```
2. Try to run the default simulation - successfully:
```
$ sbt gatling:testOnly computerdatabase.BasicSimulation
...
[info] Simulation BasicSimulation successful.
[info] Simulation(s) execution ended.
[success] Total time: 43 s, completed Nov 2, 2018 5:45:08 PM
```
3. Copy GatlingCql-0.0.8.jar into the lib/ directory 
4. Try to run the default simulation - unsuccessfully:
```
$ sbt gatling:testOnly computerdatabase.BasicSimulation
...
17:47:57.061 [ERROR] i.g.a.Gatling$ - Run crashed
java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContextBuilder.protocols([Ljava/lang/String;)Lio/netty/handler/ssl/SslContextBuilder;
...
[error] Error during tests:
[error] 	computerdatabase.BasicSimulation
[error] (Gatling / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 8 s, completed Nov 2, 2018 5:47:57 PM
```

**Comment by Mishail** [comment]
@vbachurin  Thanks for reporting. Which Gatling version do you use?

**Comment by vbachurin** [comment]
3.0.0
https://github.com/gatling/gatling.g8/blob/master/src/main/g8/default.properties
